import applications_group_representations_physics_areas_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace applications_group_representations_physics_areas_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end applications_group_representations_physics_areas_canonical_lane_mathlib
end HautevilleHouse
